### ISSUE TITLE
在MacOS 10.15.15中，该软件无法运行

### ISSUE THREAD

**Issue by weidu23** [guyoung/CaptfEncoder#10]
在MacOS 10.15.15中，安装了CaptfEncoder-app-darwin-x64-1.3.0这个版本，然后显示包内容，通过chmod +x /Applications/CaptfEncoder.app/Contents/MacOS/CaptfEncoder让文件可以被执行。
此时！
运行文件，出现错误，显示该文件无法运行，请联系作者。

**Comment by sophmore8** [comment]
Aug  3 14:30:21 macbook com.apple.xpc.launchd[1] (com.guyoung.captfencoder.43412[46733]): Could not find and/or execute program specified by service: 13: Permission denied: /Users/3333/Downloads/CaptfEncoder.app/Contents/MacOS/CaptfEncoder

**Comment by guyoung** [comment]
请试一下V3版本
