### ISSUE TITLE
mac 运行报错

### ISSUE THREAD

**Issue by simlelcf** [guyoung/CaptfEncoder#19]
mac 运行报错

1. 权限错误需要管理员权限
2. 已设置管理员权限还是报错

![image](https://user-images.githubusercontent.com/18651522/121003242-e6375900-c7bf-11eb-94f7-e75449b96b7a.png)

![image](https://user-images.githubusercontent.com/18651522/121003208-d9b30080-c7bf-11eb-9e44-683e9f3c39c4.png)

**Comment by guyoung** [comment]
mac版本没有证书签名，所以不能运行

**Comment by simlelcf** [comment]
什么时候可以支持mac,该怎么解决

**Comment by springleeo** [comment]
期待mac支持

**Comment by guyoung** [comment]
请试一下V3版本
