### ISSUE TITLE
macOS 10.14.1 不能 sudo npm start

### ISSUE THREAD

**Issue by Fre3L3i** [guyoung/CaptfEncoder#2]

**Comment by guyoung** [comment]
需要安装node.js

**Comment by 1059045463** [comment]
node.js已经安装 但是再次sudo npm install 的时候他就提示npm WARN captfencoder@1.1.0 No license field.

**Comment by 1059045463** [comment]
sudo npm start 就会出现这样的报错提示
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! captfencoder@1.1.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the captfencoder@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /User/.npm/_logs/2018-11-15T00_07_22_847Z-debug.log
