### ISSUE TITLE
V3版本如何使用

### ISSUE THREAD

**Issue by ekko-zhao** [guyoung/CaptfEncoder#50]
师傅，我看release里面是mac版本的是一个bin文件，且解压缩提示格式不对，请教下如何使用。我下载了v2版本，提示无法打开。
![image](https://user-images.githubusercontent.com/26781518/166879225-bf7e201a-ad82-4c3d-ac06-06769b7fb9eb.png)
系统版本：10.15.7
谢谢

**Comment by PrinceFPF** [comment]
chmod a+x CaptfEncoder-darwin-x64-3.1.2.bin
./CaptfEncoder-darwin-x64-3.1.2.bin
